import { createClient } from '@supabase/supabase-js';
import sharp from 'sharp';

type JsonRecord = Record<string, unknown>;

type MemberRow = {
  id: string;
  user_id: string;
  profile_photo_url: string | null;
  avatar_url: string | null;
  credentials: unknown;
};

function requiredEnv(name: string): string {
  const value = process.env[name];
  if (!value) {
    throw new Error(`Missing required env var: ${name}`);
  }
  return value;
}

function safe(value: unknown): string {
  return String(value ?? '').trim();
}

function hashString(input: string): number {
  let h = 0;
  for (let i = 0; i < input.length; i += 1) {
    h = ((h << 5) - h + input.charCodeAt(i)) | 0;
  }
  return Math.abs(h);
}

function escapeXml(value: string): string {
  return value
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&apos;');
}

function truncate(text: string, max = 90): string {
  if (text.length <= max) return text;
  return `${text.slice(0, max - 1)}…`;
}

async function fetchWithTimeout(url: string, timeoutMs = 15000): Promise<Response> {
  const ctrl = new AbortController();
  const timeout = setTimeout(() => ctrl.abort(), timeoutMs);
  try {
    return await fetch(url, { signal: ctrl.signal });
  } finally {
    clearTimeout(timeout);
  }
}

async function fetchStockAvatar(member: MemberRow): Promise<Buffer> {
  const seed = hashString(member.user_id);
  const maleIndex = seed % 100;
  const femaleIndex = (seed + 37) % 100;
  const pravatarIndex = (seed % 70) + 1;
  const sources = [
    `https://i.pravatar.cc/1200?img=${pravatarIndex}`,
    `https://picsum.photos/seed/expertly-${seed}/1400/1400`,
    `https://randomuser.me/api/portraits/men/${maleIndex}.jpg`,
    `https://randomuser.me/api/portraits/women/${femaleIndex}.jpg`,
  ];

  for (const source of sources) {
    try {
      const resp = await fetchWithTimeout(source);
      if (!resp.ok) continue;
      const arr = await resp.arrayBuffer();
      if (arr.byteLength > 0) return Buffer.from(arr);
    } catch {
      // Try next source.
    }
  }

  const initials = member.id.replaceAll('-', '').slice(0, 2).toUpperCase();
  const svg = `
    <svg width="800" height="800" xmlns="http://www.w3.org/2000/svg">
      <defs>
        <linearGradient id="g" x1="0%" y1="0%" x2="100%" y2="100%">
          <stop offset="0%" stop-color="#2563eb"/>
          <stop offset="100%" stop-color="#0b1f4d"/>
        </linearGradient>
      </defs>
      <rect width="100%" height="100%" fill="url(#g)"/>
      <circle cx="400" cy="300" r="140" fill="#ffffff" opacity="0.92"/>
      <rect x="220" y="460" width="360" height="210" rx="120" fill="#ffffff" opacity="0.92"/>
      <text x="50%" y="94%" font-size="52" text-anchor="middle" fill="#e5e7eb" font-family="Arial, sans-serif">
        ${escapeXml(initials)}
      </text>
    </svg>
  `;
  return sharp(Buffer.from(svg)).jpeg({ quality: 90 }).toBuffer();
}

async function buildCredentialImage(member: MemberRow, credential: JsonRecord, index: number): Promise<Buffer> {
  const now = new Date().toISOString().slice(0, 10);
  const title = truncate(safe(credential.name) || `Professional Credential #${index + 1}`);
  const issuer = truncate(safe(credential.issuer) || safe(credential.issuingBody) || 'Expertly Verification Desk');
  const year = safe(credential.year) || new Date().getFullYear().toString();

  const svg = `
    <svg width="1600" height="1000" xmlns="http://www.w3.org/2000/svg">
      <rect width="100%" height="100%" fill="#f8fafc"/>
      <rect x="40" y="40" width="1520" height="920" rx="20" fill="#ffffff" stroke="#dbeafe" stroke-width="4"/>
      <text x="90" y="160" font-size="58" fill="#0b1f4d" font-family="Arial, sans-serif" font-weight="700">Credential Document</text>
      <text x="90" y="250" font-size="40" fill="#1f2937" font-family="Arial, sans-serif">Name: ${escapeXml(title)}</text>
      <text x="90" y="325" font-size="38" fill="#1f2937" font-family="Arial, sans-serif">Issuer: ${escapeXml(issuer)}</text>
      <text x="90" y="400" font-size="38" fill="#1f2937" font-family="Arial, sans-serif">Year: ${escapeXml(year)}</text>
      <text x="90" y="475" font-size="34" fill="#4b5563" font-family="Arial, sans-serif">Member ID: ${escapeXml(member.id)}</text>
      <text x="90" y="545" font-size="34" fill="#4b5563" font-family="Arial, sans-serif">User ID: ${escapeXml(member.user_id)}</text>
      <text x="90" y="615" font-size="30" fill="#6b7280" font-family="Arial, sans-serif">Generated by Expertly storage backfill</text>
      <text x="90" y="680" font-size="30" fill="#6b7280" font-family="Arial, sans-serif">Generated on: ${escapeXml(now)}</text>
      <rect x="90" y="760" width="1420" height="140" rx="14" fill="#eff6ff" stroke="#bfdbfe"/>
      <text x="115" y="845" font-size="28" fill="#1d4ed8" font-family="Arial, sans-serif">
        This file is for development/demo data consistency and storage-link backfill.
      </text>
    </svg>
  `;
  return sharp(Buffer.from(svg)).png({ quality: 90 }).toBuffer();
}

async function run(): Promise<void> {
  const supabaseUrl = requiredEnv('SUPABASE_URL');
  const serviceRoleKey = requiredEnv('SUPABASE_SERVICE_ROLE_KEY');
  const forceAvatarRegenerate = process.env['FORCE_AVATAR_REGENERATE'] === 'true';

  const supabase = createClient(supabaseUrl, serviceRoleKey, {
    auth: { autoRefreshToken: false, persistSession: false },
  });

  const members: MemberRow[] = [];
  const pageSize = 500;
  for (let from = 0; ; from += pageSize) {
    const to = from + pageSize - 1;
    const { data, error } = await supabase
      .from('members')
      .select('id,user_id,profile_photo_url,avatar_url,credentials')
      .order('created_at', { ascending: true })
      .range(from, to);

    if (error) throw error;
    if (!data || data.length === 0) break;
    members.push(...(data as MemberRow[]));
    if (data.length < pageSize) break;
  }

  console.log(`Found ${members.length} members`);

  let avatarUploaded = 0;
  let credentialDocsUploaded = 0;
  let memberRowsUpdated = 0;
  let membersWithCreatedCredentials = 0;

  for (const [memberIndex, member] of members.entries()) {
    const updatePayload: Record<string, unknown> = {};

    const missingProfile = safe(member.profile_photo_url) === '';
    const missingAvatar = safe(member.avatar_url) === '';
    const shouldRefreshAvatar = forceAvatarRegenerate || missingProfile || missingAvatar;
    if (shouldRefreshAvatar) {
      const rawAvatar = await fetchStockAvatar(member);
      const processed = await sharp(rawAvatar)
        .resize(1200, 1200, { fit: 'cover', position: 'entropy' })
        .sharpen(1.1)
        .webp({ quality: 92 })
        .toBuffer();

      const avatarPath = `${member.user_id}/profile.webp`;
      const { error: uploadAvatarErr } = await supabase.storage
        .from('avatars')
        .upload(avatarPath, processed, {
          contentType: 'image/webp',
          upsert: true,
        });
      if (uploadAvatarErr) throw uploadAvatarErr;

      const { data: publicData } = supabase.storage.from('avatars').getPublicUrl(avatarPath);
      const cacheBustedUrl = `${publicData.publicUrl}?v=${Date.now()}`;
      if (forceAvatarRegenerate || missingProfile) updatePayload.profile_photo_url = cacheBustedUrl;
      if (forceAvatarRegenerate || missingAvatar) updatePayload.avatar_url = cacheBustedUrl;
      avatarUploaded += 1;
    }

    const currentCredentials = Array.isArray(member.credentials)
      ? [...(member.credentials as JsonRecord[])]
      : [];

    let credentialsTouched = false;
    if (currentCredentials.length === 0) {
      currentCredentials.push({
        id: crypto.randomUUID(),
        name: 'Professional Credential',
        issuer: 'Expertly Verification Desk',
        year: new Date().getFullYear().toString(),
      });
      membersWithCreatedCredentials += 1;
      credentialsTouched = true;
    }

    for (let i = 0; i < currentCredentials.length; i += 1) {
      const cred = { ...currentCredentials[i] };
      const existingUrl = safe(cred.url) || safe(cred.documentUrl) || safe(cred.document_url);
      if (existingUrl) {
        currentCredentials[i] = cred;
        continue;
      }

      const docBuffer = await buildCredentialImage(member, cred, i);
      const docPath = `${member.user_id}/credentials/${member.id}-${i + 1}.png`;

      const { error: uploadDocErr } = await supabase.storage
        .from('documents')
        .upload(docPath, docBuffer, {
          contentType: 'image/png',
          upsert: true,
        });
      if (uploadDocErr) throw uploadDocErr;

      const { data: signedData, error: signErr } = await supabase.storage
        .from('documents')
        .createSignedUrl(docPath, 60 * 60 * 24 * 365);
      if (signErr || !signedData?.signedUrl) throw signErr ?? new Error('Failed to sign document URL');

      cred.url = signedData.signedUrl;
      cred.documentUrl = signedData.signedUrl;
      cred.storagePath = docPath;
      currentCredentials[i] = cred;
      credentialsTouched = true;
      credentialDocsUploaded += 1;
    }

    if (credentialsTouched) {
      updatePayload.credentials = currentCredentials;
    }

    if (Object.keys(updatePayload).length > 0) {
      const { error: updateErr } = await supabase
        .from('members')
        .update(updatePayload)
        .eq('id', member.id);
      if (updateErr) throw updateErr;
      memberRowsUpdated += 1;
    }

    if ((memberIndex + 1) % 10 === 0 || memberIndex === members.length - 1) {
      console.log(`Processed ${memberIndex + 1}/${members.length} members`);
    }
  }

  console.log('Backfill complete');
  console.log(`- Member rows updated: ${memberRowsUpdated}`);
  console.log(`- Avatars uploaded: ${avatarUploaded}`);
  console.log(`- Credential docs uploaded: ${credentialDocsUploaded}`);
  console.log(`- Members with default credential created: ${membersWithCreatedCredentials}`);
}

void run().catch((error) => {
  console.error('Backfill failed:', error);
  process.exit(1);
});
